service: sos # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: ${self:custom.BUCKET_ITMES_TABLE_ARN}

functions:
  hello:
    handler: src/handler.get_one_bucket_item
    events:
      - http:
          path: /get/{id}
          method: get
  list:
    handler: src/handler.get_bucket_items
    events:
      - http:
          path: /get-bucket-items
          method: get

  create:
    handler: src/handler.create_bucket_item
    events:
      - http:
          path: /create
          method: post

plugins:
  - serverless-offline-python
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
  TABLE_NAME: 'BucketItems'
  BUCKET_ITMES_TABLE_ARN: arn:aws:dynamodb:us-east-1:792000220664:table/BucketItems


package:
  exclude:
    - venv/**
